files:
  '**/*.tf':
    - suchsatdevops
    - TheDirewolf1326
    - matheusalano
  '**/*.hcl':
    - suchsatdevops
    - TheDirewolf1326
    - matheusalano

#options:
 # number_of_reviewers: 2
numberOfReviewers: 2
