files:
  '**/*.hcl':
    - ct-eng-ops

reviewers:
  groups:
    ct-eng-ops:
      - infa-suvaddi
      - infa-kbhoyar
      - infa-svineethareddy
      
  #per_author:
   # engineers:
    #  - engineers
  
    
options:
  number_of_reviewers: 2
  enable_group_assignment: true
