addReviewers: true

groups:
    repository-owners:
      - suchsatdevops # username
      - infa-suvaddi
      - infa-kbhoyar
reviewers:
  # The default reviewers
  defaults:
    - repository-owners
    
numberOfReviewers: 2
