name: Check for istio labels in namespace

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-istio-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true

    - name: Check for istio Labels
      id: check
      continue-on-error: true
      # "bash {0}" will make all commands run regardless of any one command fails
      shell: bash {0}
      run: |
        all_files="${{ steps.files.outputs.all }}"
        if [[ ! -z "$all_files" ]];
        then
          for file in $all_files; do
            if grep -q "kind: Namespace" "$file"; then
              if grep -q "istio.io/rev" "$file"; then
                echo "comment=Error,istio.io/rev label found" >> $GITHUB_OUTPUT
                echo "Error: istio.io/rev label found in "$file"" | tee -a out.txt
              fi
            fi
          done
        fi

    - name: Update comment if istio labels found
      if: steps.check.outputs.comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          ```
          Error: istio.io/rev label found, Please remove
          ```

    - name: Fail if any istio labels present
      if: steps.check.outputs.comment
      run: |
        exit 1
