name: Check Istio Revision

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-istio-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for 'istio.io/rev'
      run: |
        if grep -r -q "istio.io/rev" ./*; then
          echo "Error: 'istio.io/rev' found in the files."
        else
          echo "No occurrence of 'istio.io/rev' found in the files."
        fi

    - name: Update comment with validation output
      if: steps.check-istio-label.outputs.comment != 'No occurrence of ''istio.io/rev'' found in the files.'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          Validation output, from ${{ github.sha }}, commit by: ${{ github.actor }}.
          ```
          istio labels are added in namespace, please remove.
          ```
    
    - name: Fail if any istio label is present
      run: |
          if: steps.check-istio-label.outputs.comment != 'No occurrence of ''istio.io/rev'' found in the files.'
          exit 1
        fi
