name: Check Istio Revision

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-istio-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for 'istio.io/rev'
      run: |
        if grep -r -q "istio.io/rev" ./*; then
          echo "Error: 'istio.io/rev' found in the files."
          exit 1
        else
          echo "No occurrence of 'istio.io/rev' found in the files."
        fi
    - name: Comment on PR
      if: steps.check-istio-label.outputs.comment != 'No occurrence of 'istio.io/rev' found in the files.'
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.check-istio-label.outputs.comment }}',
          })
