# name: Check Istio Revision

# on:
#   pull_request:
#     paths:
#       - '**'

# jobs:
#   check-istio-label:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: Check for 'istio.io/rev'
#       run: |
#         if grep -r -q "istio.io/rev" ./*; then
#           echo "Error: 'istio.io/rev' found in the files."
#         else
#           echo "No occurrence of 'istio.io/rev' found in the files."
#         fi

#     - name: Update comment with validation output
#       if: steps.check-istio-label.outputs.comment != 'No occurrence of ''istio.io/rev'' found in the files.'
#       uses: marocchino/sticky-pull-request-comment@v2
#       with:
#         recreate: true
#         message: |
#           Validation output, from ${{ github.sha }}, commit by: ${{ github.actor }}.
#           ```
#           istio labels are added in namespace, please remove.
#           ```
    
#     - name: Fail if any istio label is present
#       run: |
#           if: steps.check-istio-label.outputs.comment != 'No occurrence of ''istio.io/rev'' found in the files.'
#           exit 1
#         fi

name: Check Istio Revision

on:
  pull_request:
    paths:
      - '**'

jobs:
  check-istio-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1
      continue-on-error: true

    - name: Check for Namespace Labels
      id: check
      continue-on-error: true
      # "bash {0}" will make all commands run regardless of any one command fails
      shell: bash {0}
      run: |
        all_files="${{ steps.files.outputs.all }}"
        if [[ ! -z "$all_files" ]];
        then
          for file in $all_files; do
            if grep -q "kind: Namespace" "$file"; then
              if grep -q "istio.io/rev" "$file"; then
                echo "Error: Namespace labels found in "$file"" | tee -a out.txt
              fi
            fi
          done
        fi

    - name: Update comment with validation output
      #if: steps.check.out.txt != ''
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        message: |
          ```
          ${{ steps.check.outputs.result }}
          ```

    - name: Fail if any of istio labels present
      run: |
        if grep Error out.txt > /dev/null 2>&1; then 
          exit 1
        fi
