name: 'Validate PR file'
on:
  pull_request:
    paths:
      - '!src/**/*.hcl'
      - '!src/**/*.tf'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1

    - name: Get changed files in the messages folder
      id: changed-files-specific
      uses: jitterbit/changed-files@v34
      with:
        files: |
          messages/**
    
    - name: Add number of reviewers
      run: |
        all_files="${{ steps.changed-files-specific.outputs.any_changed }}"
        if [[ ! -z "$all_files" ]];
        then
          number_of_reviewers: 2
        fi
