name: 'Create PR file'
on:
  pull_request:
    paths:
      - 'src/**/*.txt'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          src/**/main/**/*.txt
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
          
    - name: Request review based on files changes
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: infa-suvaddi,infa-kbhoyar,infa-pthimmap
        minimum-approvals: 2
