name: 'Validate PR file'
on:
  pull_request:
    paths:
      - 'src/**/*.hcl'
      - 'src/**/*.tf'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Get changed files in the terraform folder
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          src/**/main/**
          

    - name: Auto request review
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: necojackarc/auto-request-review@v0.9.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/assign-by-files.yml
