name: 'Validate PR file'
on:
  pull_request:
    paths:
      - 'src/**/*.hcl'
      - 'src/**/*.tf'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1
    
    - name: Add number of reviewers
      run: |
        all_files="${{ steps.files.outputs.all }}"
        if [[ ! -z "$all_files" ]];
        then
          for file in $all_files; do
            if [[ ( "$(basename $file)" == "*.tf" || "$(basename $file)" == "*.hcl" ) && -n $(echo "$file" | grep "src/main") ]];
            then
              numberOfReviewers: 2
            else
              numberOfReviewers: 2
            fi
          done
        fi
