name: 'Validate PR file'
on:
  pull_request:
    types:
      [
        assigned,
        unassigned,
        opened,
        reopened,
        synchronize,
        review_requested,
        review_request_removed
      ]
    paths:
      - 'src/**/*.hcl'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          src/**/main/**/*.hcl
          

   # - name: Request review based on files changes
    #  if: steps.changed-files-specific.outputs.any_changed == 'true'
    #  uses: necojackarc/auto-request-review@v0.9.0
     # with:
         # token: ${{ secrets.GITHUB_TOKEN }}
         # config: .github/reviewers.yml
  
    - name: Request for minimum 2 approvals
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: octodemo/pr-gatekeeper@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
