name: 'Minimum number of approvers'
on:
  pull_request_review:
    paths:
      - 'src/**/*.hcl'
  pull_request:
    paths:
      - 'src/**/*.hcl'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Request for minimum 2 approvals
      uses: octodemo/pr-gatekeeper@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
