name: 'Minimum number of approvers'
on:
  pull_request_review:
  pull_request:
    paths:
      - 'src/**/*.hcl'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'
      
    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1

    - name: Request for minimum 2 approvals
      if: contains('["test.hcl"]', "${{ steps.files.outputs.all }}")
      uses: octodemo/pr-gatekeeper@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
