name: 'Validate PR file'
on:
  pull_request:
    paths:
      - '!src/**/*.hcl'
      - '!src/**/*.tf'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1

    #- name: Get changed files in the messages folder
      #id: changed-files-specific
      #uses: jitterbit/changed-files@v34
      #with:
        #files: |
          #messages/**
    
    - name: Add number of reviewers
      run: |
        all_files="${{ steps.files.outputs.all }}"
        if [[ ! -z "$all_files" ]];
        then
          for file in $all_files; do
            if [[ ( "$(basename $file)" == "*.tf" || "$(basename $file)" == "*.hcl" ) && -n $(echo "$file" | grep "src/main") ]];
            then
              number_of_reviewers: 2
            else
              number_of_reviewers: 2
            fi
          done
        fi
