name: 'Validate PR file'
on:
  pull_request:
    paths:
      - 'src/**/*.hcl'
      - 'src/**/*.tf'

jobs:
  validate-pr:
    name: Validate pr
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout code'
      uses: 'actions/checkout@v2'

    - name: Identify all files in PR
      id: files
      uses: jitterbit/get-changed-files@v1
    
    - name: Auto assign number of reviewers based on files changed
      uses: shufo/auto-assign-reviewer-by-files@v1.1.4
      continue-on-error: true
      # "bash {0}" will make all commands run regardless of any one command fails
      shell: bash {0}
      run: |
        all_files="${{ steps.files.outputs.all }}"
        if [[ ! -z "$all_files" ]];
        then
          for file in $all_files; do
            if [[ ( "$(basename $file)" == "test.tf" || "$(basename $file)" == "test.hcl" ) && -n $(echo "$file" | grep "src/main") ]];
            then
              config: ".github/assign-by-files.yml"
              token: ${{ secrets.GITHUB_TOKEN }}
            fi
          done
        fi
